theme: jekyll-theme-minimal
name: "Zoe Vernon"
markdown: kramdown
minimal_mistakes_skin: "contrast"
locale: "en-US"
title: "Zoe Vernon"
title_separator: "|" 
description: "Personal webpage for Zoe Vernon"
url: "https://zoevernon.github.io/"
repository: "zoevernon/zoevernon.github.io"
